from typing import Protocol


class ClockPort(Protocol):
    def current_time(self) -> tuple[int, int]: ...


class BuzzerPort(Protocol):
    def beep_on(self) -> None: ...
    def beep_off(self) -> None: ...


class LedPort(Protocol):
    def flash_on(self) -> None: ...
    def flash_off(self) -> None: ...


class ButtonPort(Protocol):
    def is_pressed(self) -> bool: ...
